# Generated by Django 6.0.6 on 2026-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='name',
            field=models.CharField(default='Promo Deal', max_length=100),
        ),
    ]
