# Generated by Django 6.0.6 on 2026-07-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0002_promocode_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='codename',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='condition',
        ),
    ]
