# Generated by Django 6.0.6 on 2026-07-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('vehicle', models.CharField(max_length=255)),
                ('pickup_date', models.CharField(max_length=100)),
                ('dropoff_date', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField(default=0)),
                ('promo_code', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('total_cost', models.IntegerField()),
                ('status', models.CharField(choices=[('booking', 'Booking'), ('renting', 'Renting'), ('rented', 'Rented')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
