# Generated by Django 6.0.6 on 2026-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booking', 'Booking'), ('renting', 'Renting'), ('rented', 'Rented')], default='active', max_length=20),
        ),
    ]
