# Generated by Django 6.0.6 on 2026-06-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='ev', max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.CharField(blank=True, default='/image/xiaomi-su7.jpg', max_length=500)),
            ],
        ),
    ]
