# Generated by Django 6.0.3 on 2026-06-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.CharField(default='/image/xiaomi-su7.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('ev', 'EV Car'), ('fuel', 'Fuel Combustion'), ('bike', 'Super Bike')], default='ev', max_length=10),
        ),
    ]
