# Generated by Django 6.0.6 on 2026-06-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_badge_icon_vehicle_badge_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='badge_icon',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='badge_label',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.CharField(blank=True, default='/image/xiaomi-su7.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(default='ev', max_length=50),
        ),
    ]
